### ISSUE TITLE
TypeError: Cannot read property 'disable-hfs' of undefined

### ISSUE THREAD

**Issue by protw** [TheDiveO/ThirdFlow#11] opened 2017-03-21 16:13 UTC
I'm not a plugin developer trying instead to use TheDiveO plugin for TW5 supposedly having a large number of files. That is why splitting the whole bunch of tiddlers by tag driven folders is seen very useful.

I just dowloaded 'thirdflow.tid' from http://thediveo.github.io/ThirdFlow/ and drag-and-dropped it into a bare node.js driven TW5.

However, during launch I've got the following error message:

```
D:\boa_protw\5064-protw5-svob>call tiddlywiki ./wiki --server 5064 $:/core/save/all text/plain text/html "" "" 127.0.0.1
HierarchicalFileSystem: folder policy config: default: hierarchical subfolders are enabled
HierarchicalFileSystem: folder policy config: draft: draft subfolder is: drafts
HierarchicalFileSystem: folder policy config: system: system subfolder is: system
HierarchicalFileSystem: folder policy config: tag: for: "Налаштування та інструменти" folder: "налаштування та інструменти" mode: subfolders
HierarchicalFileSystem: folder policy config: tag: for: "Нові проекти" folder: "нові проекти" mode: subfolders
HierarchicalFileSystem: 4 folder policies active

$:/plugins/TheDiveO/ThirdFlow/syncadapters/hierarchicalfilesystemadaptor.js:86
        if($tw.boot.wikiInfo.config["disable-hfs"]) {
                                   ^
TypeError: Cannot read property 'disable-hfs' of undefined
    at new HierarchicalFileSystemAdaptor ($:/plugins/TheDiveO/ThirdFlow/syncadapters/hierarchicalfilesystemadaptor.js:86:29)
    at $:/core/modules/startup.js:96:22
    at C:\Users\Admin\AppData\Roaming\npm\node_modules\tiddlywiki\boot\boot.js:747:3
    at $tw.utils.each (C:\Users\Admin\AppData\Roaming\npm\node_modules\tiddlywiki\boot\boot.js:78:12)
    at Object.$tw.modules.forEachModuleOfType (C:\Users\Admin\AppData\Roaming\npm\node_modules\tiddlywiki\boot\boot.js:746:12)
    at Object.exports.startup ($:/core/modules/startup.js:94:14)
    at $tw.boot.executeNextStartupTask (C:\Users\Admin\AppData\Roaming\npm\node_modules\tiddlywiki\boot\boot.js:1959:10)
    at $tw.boot.executeNextStartupTask (C:\Users\Admin\AppData\Roaming\npm\node_modules\tiddlywiki\boot\boot.js:1963:21)
    at $tw.boot.executeNextStartupTask (C:\Users\Admin\AppData\Roaming\npm\node_modules\tiddlywiki\boot\boot.js:1963:21)
    at $tw.boot.startup (C:\Users\Admin\AppData\Roaming\npm\node_modules\tiddlywiki\boot\boot.js:1916:11)
```

Could you tell me please what I did wrong?

**Comment by TheDiveO** [comment] 2017-03-25 19:59
Which version of tw5 do you use, that is, which version did you install using npm?

**Comment by protw** [comment] 2017-03-26 12:19
node 6.9.4
npm 4.3.0
tiddlywiki 5.1.13

**Comment by TheDiveO** [comment] 2017-03-31 10:06
Unfortunately, I cannot reproduce using stable node 4.6.x and tiddlywiki 5.1.13.

**Comment by TheDiveO** [comment] 2017-03-31 10:47
Okay, after checking with Jeremy Ruston I think I understand the issue and have an idea how to fix it.

**Comment by protw** [comment] 2017-03-31 11:22
Thanks. I'll be waiting for the result from you.

**Comment by TheDiveO** [comment] 2017-04-01 17:29
@protw can you please test the new release? https://github.com/TheDiveO/ThirdFlow/releases/tag/v1.0.13

**Comment by protw** [comment] 2017-04-02 13:47
thanks, I will

**Comment by protw** [comment] 2017-04-02 14:56
Great - TW is launched successfully.

However, the plugin seems to work not as I expected according to http://thediveo.github.io/ThirdFlow/:

- I installed tiddlywiki 5.1.13 under node.js 6.9.4, OS Windows 10/64bit
- I dragged-and-dropped the latest ThirdFlow 1.0.13 what you just pointed out
- I set parameters as prescribed in the documentation:
-- `Organize ordinary tiddlers into hierarchical subfolders` - ON
-- corresponding `Tag-based Folders` are set as `subfolders`.
- But the plugin succeeded to create tag-based folders and locate in them tiddlers only for tiddlers having both `titles` and `tags` in **Latin**. For those tiddlers having whether `title` or `tag` in **Cyrillic** the plugin does not work properly leaving those tiddlers in the root folder without creating tag-named subfolders.

Looking forward to hearing from you on the issue.

**Comment by TheDiveO** [comment] 2017-04-02 18:55
Glad to hear that the bug is now fixed, so I can close this issue. Please file a new issue, it doesn't help to drag issues out into new topics. I have to admit that I don't know why there are problems with Cyrillic, matching should work; but I've seen that Jeremy has added some special support, which I yet don't exactly understand. Unfortunately, I don't have time at the moment to look into the new issue, I'm afraid.

**Closed by TheDiveO** 2017-04-02 18:55 UTC
Labels: bug

**Comment by protw** [comment] 2017-04-02 18:59
Anyway thanks for your efforts.

Do you pass the issue with Cyrillic to Jeremy?
